# https://developermail.io/docs

developermail.io:
  spencer:
    aliases: [boucher, justmytwospence, spence, spencer.boucher, spencer.g.boucher]
    sieve: sieve/default.sieve
spencerboucher.com:
  spencer:
    aliases: [contact, me]
