# https://developermail.io/docs

developermail.io:
  spencer:
    aliases: [spencer.boucher, spencer.g.boucher]
    sieve: sieve/default.sieve

spencerboucher.com:
  spencer:
    aliases: [boucher, contact, justmytwospence, me, spence, spencer.boucher, spencer.g.boucher]
    sieve: sieve/default.sieve
