# https://developermail.io/docs

spencerboucher.com:
  spencer:
    aliases: [boucher, contact, email, justmytwospence, mail, me, s, spence, spencer.boucher, spencer.g.boucher]
    sieve: sieve/default.sieve
